### ISSUE TITLE
Obtenção dos dados Y para Quito

### ISSUE THREAD

**Issue by ronaldonunes** [mcf1110/smart-cities-pollution#2]
Busquei os dados em algumas fontes:

https://aqicn.org/data-platform/register/
https://data.mendeley.com/datasets/dcj58524fk/1
https://data.mendeley.com/datasets/trs5j932s8/1
https://openaq.org/#/countries/EC
http://www.quitoambiente.gob.ec/ambiente/index.php/descarga-datos-historicos

A fonte com os melhores dados foi http://www.quitoambiente.gob.ec/ambiente/index.php/descarga-datos-historicos.

Como a média e a mediana dos dados são próximas fiz a média dos dados para Abril de 2019.

Foi possível ter apenas 7 pontos ( 7 estações de medição).

Ver https://github.com/mcf1110/smart-cities-pollution/blob/main/data/Quito/QuitoDataframe.ipynb

**Comment by mcf1110** [comment]
Maravilha, @ronaldonunes!

Algumas coisas que quero deixar anotado aqui (mesmo que seja para eu mesmo corrigir semana que vem haha):

- Parece que o período considerado termina às 0h00 de 30/04 (ou seja, 24h00 do dia 29). Querendo ou não, está ignorando um dia. Não deve distorcer muito a média, mas acho melhor arrumar isso por garantia 😄 
- Os dados são só referentes ao NO2, certo? Depois temos que dar uma procurada em NO e BC tb
- Particularmente, acho mais portátil usar um csv para armazenar os dados em vez de um pickle. Isso é bem simples de arrumar também, e pode ficar para depois 😉

**Comment by ronaldonunes** [comment]
**Problemas Solucionados:**

-  Média sobre todos os dados de 0h00 de 01/04/2019 até 23h00 de 30/04/2019
-  Dados armazenados em csv

**Problema ainda não solucionado:**

- NO e BC para Quito. Não achei essa informação em nenhum dos dataset que vi para Quito.

**Comment by mcf1110** [comment]
Rapaz, que eficiência! 😄 

Beleza, podemos procurar com calma nas próximas semanas
